version: "3.8"

services:
    copydb:
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        command: ./copydb.sh
        sysctls:
            - net.ipv4.tcp_keepalive_time=200
            - net.ipv4.tcp_keepalive_intvl=200
            - net.ipv4.tcp_keepalive_probes=5
        labels:
            org.label-schema.name: "pgsync"
            org.label-schema.description: "Postgres to Elasticsearch sync"
            com.label-schema.service-type: "daemon"
        environment:
            - STAGING_DATABASE_URL=postgresql://staging_database_fnae_user:uzNuADrP9xfYz86cyTsA9BRXCddSL9Hs@dpg-cqhvkkhu0jms739e2p2g-a.oregon-postgres.render.com/staging_database_fnae
            - PRODUCTION_DATABASE_URL=postgres://perfectly_imperfect_prod_db_user:aPF1AUKnDN3cQ7EZVJWM05MmksAI8JHk@dpg-cg7o8gseoogs6a36mihg-a.oregon-postgres.render.com/perfectly_imperfect_prod_db?sslmode=require
